# Generated by Django 3.2.25 on 2025-05-29 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_nom_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_naissance',
            field=models.DateField(default=datetime.date(2025, 5, 29)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='genre',
            field=models.CharField(blank=True, choices=[('H', 'Homme'), ('F', 'FEMME')], max_length=1, null=True),
        ),
    ]
